removed useless conversions
wirenboard/wb-rules-system pull request #10
Opened 2020-03-29 13:55 UTC by nlef

2020-03-29 22:19 UTC, wierdbytes requested changes
В этом случае в mqtt могут уходить очень "длинные" значения. Напрмер:
```
/devices/hwmon/controls/CPU Temperature 59.974000000000004
```

В интерфейсе это тоже не совсем хорошо выглядит.

2020-03-30 04:42 UTC, nlef commented
@wierdbytes но в данном случае при чтении приходит Int, указанная далекая дробная часть откуда может появится?

2020-04-03 20:47 UTC, nlef commented
@wierdbytes Проверил в данном конкретном месте - длинной дробной части не получается.
https://jsperf.com/flooring-benchmark основываясь на этом бенчмарке - двойной парсинг строк будет серьезно загружать процессор впустую.

2020-04-04 19:27 UTC, nlef commented
@wierdbytes добавил округление до целого после парсинга float из строки. Быстро и с гарантией отсечки. на основе [этой статьи](https://j11y.io/javascript/double-bitwise-not/)

2022-09-15 15:16 UTC, webconn commented
Двойное отрицание не поможет округлить в данном случае, потому что сразу после этого мы домножаем на 0.001 и ошибка появляется после умножения. Пример строки, на которой воспроизводится - `"99094"`.

Впрочем, если убрать `parseInt`, оставив при этом `.toFixed(3)`, действительно получается примерно в три раза быстрее, на моём бенчмарке 350 мс против 1100 у текущего решения.

Единственное, я не уверен, влияет ли это на что-либо в рамках этих правил. Они вызываются довольно редко, и вычисление занимает порядка 0.1 мс.

Этот PR я закрою, а исправление сделаю отдельной веткой, заодно увеличив версию пакета.

Спасибо за PR, а также прошу прощения за столь долгую задержку с ответами

2022-09-15 15:16 UTC, closed without merging