add wbmz2-battery module
wirenboard/wb-rules-system pull request #12
Opened 2020-04-09 17:46 UTC by munrexio

2020-04-10 08:31 UTC, evgeny-boger requested changes

2020-04-10 08:31 UTC, evgeny-boger commented on debian/wb-rules-system.dirs
> +etc
это не нужно

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +var wbmz2_ps = new PersistentStorage("wbmz2-battery", {global: true}); // Глобальное хранилище для калибровочных значений
вообще persistentstorage появился в 1.7, поэтому в debian/control надо поставить зависимость от wb-rules >= 1.7, если ещё не.

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +var startChargeCorrection = 0; // Калибровочное значение по умолчанию
наверное лучше 1500 записать

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +    title: "WBMZ2 Battery",
WBMZ2-BATTERY , модуль именно так называется.

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        type: "current",
здесь и везде: форматирование надо как в соседних файлах: 4 пробела на отступ, открывающаяся фигурная скобочка остаётся в той же строчке.

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +  if(!wbmz2_ps.correction){
здесь и далее: пробелы как в соседних файлах

```
if(!wbmz2_ps.correction){
```
=>
```
if (!wbmz2_ps.correction) {
```

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +      }else{
```} else {```

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        /*
комментарий бессмыленный, если хочется оставить - то в одну строчку: 
```
/* Current - ток */
```
или
```
// Current - ток
```

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        /*
в одну строчку комментарий

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        var currentRaw = parseInt("0x"+arrayOfData[6]+arrayOfData[5], 16);
кажется, что если написано 16, то 0x уже можно не добавлять

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        то вписываем это значение в хранилище wbmz2_ps.correction без отрицательного знака.
тут в комментарии дословно описан дальнейший код, так не надо делать. Я бы так написал: "Если вычисленная ёмкость оказалась меньше нуля, то обновляем значение коррекциии"

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        if((charge_mah < 0) && ((-charge_mah) > wbmz2_ps.correction)){
а тут точно условие `charge_mah < 0` правильно? У нас же само абсолютное значение с батарейки почти любое: если особо хитро отключать аккумулятор от платки и подключать обратно, то его можно сильно в плюс увести.
По-моему это условие надо просто удалить, оставить 
```charge_mah + wbmz2_ps.correction < 0```

2020-04-10 08:31 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +        dev['wbmz2-battery']['charge'] = Math.round((charge_mah + wbmz2_ps.correction)* 100) / 100;
пробел перед звёздочкой

2020-04-13 18:52 UTC, evgeny-boger commented on rules/wbmz2-battery.js
> +var batteryСapacity = 2500;
это я не очень понял. Как это работает?

2020-04-15 07:40 UTC, munrexio commented on rules/wbmz2-battery.js
> +        var currentRaw = parseInt("0x"+arrayOfData[6]+arrayOfData[5], 16);
Мне тоже так казалось, пробовал - не работает

2020-04-15 07:43 UTC, munrexio commented on debian/wb-rules-system.dirs
> +etc
Без этого пакет не собирается на билд сервере

2020-04-18 17:40 UTC, merged