Feature/add disk space
wirenboard/wb-rules-system pull request #16
Opened 2020-07-01 17:59 UTC by brainroot

Добавил скрипт для вывода занятого/свободного места на /mnt/data
Время обновления - специально не кратно минуте, чтоб в одно и тоже не запускались.

2020-07-01 22:35 UTC, evgeny-boger requested changes

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +  title: "Disk Space",
не лучше ли добавить это в /devices/system/ ?

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +defineVirtualDevice("freeDiskSpace", {
остальные не в camelCase называются

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +    type: "text",
почему text, если это число? Думаю лучше value

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +  cells:
весь этот кусок кода не отформатирован. Форматирование должно быть такое же, как в соседних файлах, если нет стайлгайда.

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +    value: "99"
почему по-умолчанию 99?

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +  runShellCommand("df -k /mnt/data | tail -1", {
а почему только /mnt/data ?

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +      var CapturedSeparated = capturedOutput.split(/\s+/);
переменные с маленькой буквы в соседних файлах

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +      log.info("CapturedSeparated ",CapturedSeparated);
отладочного вывода в продакшне лучше не делать

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +      dev["freeDiskSpace"]["Avaliable_kB"] = CapturedSeparated[3]; //Avaliable
комментарии здесь бесполезные, их лучше убрать

2020-07-01 22:35 UTC, evgeny-boger commented on rules/disk_space.js
> +updateFreeDiskSpace();
кажется, обращение к dev[] за пределами таймеров и правил - это нехорошо.

2020-07-02 17:04 UTC, brainroot commented on rules/disk_space.js
> +  title: "Disk Space",
Да, добавил в файл system.js

2020-07-02 17:05 UTC, brainroot commented on rules/disk_space.js
> +    type: "text",
Исправил. Пришлось тип привести.

2020-07-02 17:05 UTC, brainroot commented on rules/disk_space.js
> +    value: "99"
Поставил 0

2020-07-02 17:06 UTC, brainroot commented on rules/disk_space.js
> +  runShellCommand("df -k /mnt/data | tail -1", {
Переделал проверку в функцию, в которую передаем путь для проверки и имя для интерфейса.
Чтоб не быдлкодить копипастой вконец.
Проверяется / и data

2020-07-02 17:10 UTC, brainroot commented on rules/disk_space.js
> +      log.info("CapturedSeparated ",CapturedSeparated);
Удалил.

2020-07-02 17:10 UTC, brainroot commented on rules/disk_space.js
> +      dev["freeDiskSpace"]["Avaliable_kB"] = CapturedSeparated[3]; //Avaliable
Удалил, да, верно.

2020-07-02 17:10 UTC, brainroot commented on rules/disk_space.js
> +updateFreeDiskSpace();
Функция вызывается исключительно из таймера,

2020-07-03 07:02 UTC, brainroot reviewed
Понял. Думал "вторая" цифра - это младшая.

2020-07-03 08:41 UTC, evgeny-boger commented
речь про вот это была: https://semver.org/lang/ru/
У нас по нему.

2020-10-16 07:36 UTC, evgeny-boger requested changes
ещё поигрался, пока не нравится. 
1) 2.5 минуты до первого появления данных - долго, это заметно. Установил пакет, вижу нули в интерфейсе.
2) Очень много чисел. Наверное есть смысл оставить только Used, % для каждого раздела.

2020-10-16 07:45 UTC, brainroot commented
Да, переделаю. 
Будем вызывать однократно функцию при запуске - чтобы заполнились сразу. Остальное (лишние значения) - предлягаю закомментировать, кому надо - откроет. Хотя и по аналогии сделает, можно удалить.

2022-08-23 09:34 UTC, webconn commented
Этот функционал в каком-то виде въехал в `wb-mqtt-metrics`, PR висит два года, закрываю за невостребованностью.

2022-08-23 09:34 UTC, closed without merging