add support for battery and supercap modules on WB7
wirenboard/wb-rules-system pull request #24
Opened 2022-02-13 19:11 UTC by evgeny-boger

на WB6 пока не проверил

2022-02-17 19:12 UTC, webconn requested changes

2022-02-17 19:12 UTC, webconn commented on rules/power-class-battery.js
> +                    getControl("battery/Charging").setValue({value: !newState, notify: false});
Очепятка, тут должно быть не `newState`, а `newValue`.

И мысль в копилку вопросов к новой конвенции, как красивее обращаться со свитчами, которые могут и не переключиться по какой-то своей причине.

2022-02-17 19:12 UTC, webconn commented on rules/power-class-battery.js
> +setInterval(collectData, updateIntervalMs);
А почему не в один таймер?

2022-02-20 20:15 UTC, evgeny-boger commented on rules/power-class-battery.js
> +setInterval(collectData, updateIntervalMs);
fixed

2022-02-20 20:15 UTC, evgeny-boger commented on rules/power-class-battery.js
> +                    getControl("battery/Charging").setValue({value: !newState, notify: false});
fixed

2022-02-21 08:09 UTC, webconn approved these changes

2022-02-22 20:53 UTC, webconn approved these changes

2022-02-23 15:29 UTC, merged