network: fix 'Active Connection Name' control, cleanup logs
wirenboard/wb-rules-system pull request #35
Opened 2023-01-10 12:58 UTC by sikmir

Changelog:
1. Почистил спам в логи
2. Починил Active Connection Name контрол (если активных соединений несколько, то выводились все, теперь только то, через которое есть доступ в интернет)

2023-01-10 16:08 UTC, webconn requested changes
На самом деле мне нравилось, что в `Active Connection` выводился список всех активных соединений, по этой штуке можно было отлаживаться в каком-то смысле. Понятно, что сейчас правильней. А давай сделаем контрол `Active Connections`, в котором будет JSON-массив всех активных соединений (отсортированных по имени, чтобы было меньше вариативности), а тот, который сейчас называется `Active Connection Name` переименуем в `Internet Connection`

2023-01-10 16:08 UTC, webconn commented on rules/buzzer.js
> +      runShellCommand("echo {} > {}/export".format(pwm_number, pwm_sys));
Тут бы ещё сразу проверять, что `pwm1` не существует, а то при перезапуске wb-rules вылетает

```
Jan 10 15:26:45 wirenboard-ATHFDT4L wb-rules[31881]: /bin/sh: 1: echo: echo: I/O error
Jan 10 15:26:45 wirenboard-ATHFDT4L wb-rules[30969]: ERROR: command '/bin/sh -c echo 1 > /sys/class/pwm/pwmchip0/export' failed with exit status 1
```

2023-01-10 16:08 UTC, webconn commented on rules/network.js
> +      dev.network["Default Interface"] = exitCode === 0 ? capturedOutput : "";
```suggestion
      dev.network["Default Interface"] = exitCode === 0 ? capturedOutput.trim() : "";
```

Без этого Active Connection у меня не заработало, кажется, там `\n` был лишним

2023-01-10 16:08 UTC, webconn commented on rules/network.js
> +          dev.network["Active Connection Name"] = lines[i].split(":")[1];
```suggestion
          dev.network["Active Connection Name"] = lines[i].split(":")[1].trim();
```

Ну чтобы уж наверняка

2023-01-10 16:08 UTC, webconn commented
А срача в логах и правда стало меньше :muscle:

2023-01-10 17:02 UTC, sikmir commented
<img width="455" alt="Screen Shot 2023-01-10 at 20 01 43" src="https://user-images.githubusercontent.com/688044/211615368-55643429-ba27-4446-bfab-f2406193c6bc.png">

2023-01-10 17:03 UTC, sikmir commented on rules/network.js
> +      dev.network["Default Interface"] = exitCode === 0 ? capturedOutput : "";
поправил

2023-01-10 17:04 UTC, sikmir commented on rules/network.js
> +          dev.network["Active Connection Name"] = lines[i].split(":")[1];
поправил

2023-01-10 21:36 UTC, sikmir commented on rules/buzzer.js
> +      runShellCommand("echo {} > {}/export".format(pwm_number, pwm_sys));
А что значит `pwm1` не существует? `/sys/class/pwm/pwmchip0/pwm1` есть (по крайней мере на WB7).
```sh
. /etc/wb_env.sh && echo -n $WB_PWM_BUZZER
```
возвращает 1, то есть получаем:
```sh
echo 1 > /sys/class/pwm/pwmchip0/export
write: Device or resource busy
```

2023-01-11 06:27 UTC, KraPete commented on rules/network.js
> +      dev.network["Active Connections"] = JSON.stringify(active_connections.sort());
А если их выводить списком с разделителем `\n`?

2023-01-11 06:28 UTC, KraPete commented on rules/network.js
> +      dev.network["Active Connections"] = JSON.stringify(active_connections.sort());
А если их выводить списком с разделителем `\n`?

2023-01-11 06:38 UTC, sikmir commented on rules/network.js
> +      dev.network["Active Connections"] = JSON.stringify(active_connections.sort());
UI не покажет `\n`, заменит на пробел.

2023-01-11 06:44 UTC, KraPete requested changes
Можно ещё сразу поправить порядок контролов? Почему то сначала идут `Ethernet 2` и `Wi-Fi 2`.

2023-01-11 06:53 UTC, sikmir commented
> Можно ещё сразу поправить порядок контролов? Почему то сначала идут `Ethernet 2` и `Wi-Fi 2`.

Отсортировал в коде, как они сортируются на UI.

2023-01-11 07:15 UTC, KraPete commented
> > Можно ещё сразу поправить порядок контролов? Почему то сначала идут `Ethernet 2` и `Wi-Fi 2`.
> 
> Отсортировал в коде, как они сортируются на UI.

Я не то имел ввиду. Сначала идёт `Ethernet IP 2`, а потом `Ethernet IP` и для  Wi-Fi то же

2023-01-11 07:39 UTC, sikmir commented
> > > Можно ещё сразу поправить порядок контролов? Почему то сначала идут `Ethernet 2` и `Wi-Fi 2`.
> > 
> > 
> > Отсортировал в коде, как они сортируются на UI.
> 
> Я не то имел ввиду. Сначала идёт `Ethernet IP 2`, а потом `Ethernet IP` и для Wi-Fi то же

Вот так тогда:
<img width="459" alt="Screen Shot 2023-01-11 at 10 38 36" src="https://user-images.githubusercontent.com/688044/211745910-e1f32428-01af-4c63-b495-ea1e1363e382.png">

2023-01-11 07:53 UTC, KraPete approved these changes

2023-01-11 08:41 UTC, webconn commented on debian/changelog
>  wb-rules-system (1.8.6) stable; urgency=medium
`1.9.0` можно, изменения затрагивают названия контролов

2023-01-11 08:41 UTC, webconn commented on rules/buzzer.js
> +      runShellCommand("echo {} > {}/export".format(pwm_number, pwm_sys));
Ну вот примерно в этом и проблема, в логах появляется ERROR, потому что мы пытаемся сделать `export` для `pwm`, который уже экспортирован. А на деле это не ошибка.

Логика нужна в духе

```
if (!exists("/sys/class/pwm/pwmchip0/pwm1")) {
  runShellCommand(...)
}
```

2023-01-11 08:59 UTC, sikmir commented on debian/changelog
>  wb-rules-system (1.8.6) stable; urgency=medium
увеличил

2023-01-11 09:00 UTC, sikmir commented on rules/buzzer.js
> +      runShellCommand("echo {} > {}/export".format(pwm_number, pwm_sys));
Добавил проверку `[ -e /sys/class/pwm/pwmchip0/pwm1 ] || echo 1 > /sys/class/pwm/pwmchip0/export`.

2023-01-12 14:40 UTC, sikmir commented on rules/buzzer.js
> +      runShellCommand("echo {} > {}/export".format(pwm_number, pwm_sys));
@webconn так ОК? вливаем?

2023-01-12 14:43 UTC, webconn approved these changes
В остальном lgtm

2023-01-12 14:43 UTC, webconn commented on rules/buzzer.js
> +      runShellCommand("[ -e /sys/class/pwm/pwmchip0/pwm{0} ] || echo {0} > {1}/export".format(pwm_number, pwm_sys));
```suggestion
      runShellCommand("[ -e {1}/pwm{0} ] || echo {0} > {1}/export".format(pwm_number, pwm_sys));
```

2023-01-12 14:54 UTC, merged