Переработка основных правил
wirenboard/wb-rules-system pull request #46
Opened 2024-04-26 04:54 UTC by alexey-gamov

* Упрощение кода где это возможно (убраны или упрощены функции)
* Расстановка порядка вывода контроллов

Ошибок скрипты не вызывают, тк в основном все оттестировано (кроме `wbmz-battery.js`).
Браться за `power-class-battery.js` не стал, слишком уж все запутано для меня :)

2024-05-02 08:19 UTC, ninedev-i requested changes
Тут какая-то проблема то-ли с линтером, то-ли с настройками отступов в редакторе кода. Ревьюить такое очень сложно, откатите пожалуйста к дефолтным отступам

2024-05-04 11:49 UTC, alexey-gamov commented
В большинстве скриптов сильно изменена структура, передвинуты куски из отдельных функций в основные.

Общая логика не менялась и результаты дает те же что и до «оптимизации».

Не думаю что табуляция даст больше в визуальном сравнении.

2024-05-06 06:30 UTC, ninedev-i commented
У нас есть [правила кодстайла](https://github.com/wirenboard/codestyle/blob/master/js/prettierrc#L13), где есть правило что мы не используем табы, а используем пробелы. Отформатируй код, пожалуйста, под принятые стандарты.

2024-05-27 10:19 UTC, ninedev-i approved these changes
lgtm

2025-06-17 04:56 UTC, closed without merging